-- Function: getexistchaveacesso(text, text)

CREATE OR REPLACE FUNCTION getexistchaveacesso(
    cnpj text,
    chaveacesso text)
  RETURNS text AS
$BODY$
 DECLARE 
    RCHAVEACESSO RECORD;
    pCNPJ ALIAS FOR $1;
    pCHAVEACESSO ALIAS FOR $2;
BEGIN
 SELECT INTO RCHAVEACESSO CHAVEACESSO.CNPJ, CHAVEACESSO.CHAVE, CHAVEACESSO.ALTERARLOCALIZACAO FROM DADOS.CHAVEACESSO WHERE CHAVEACESSO.CNPJ = CAST(pCNPJ AS VARCHAR(14)) AND CHAVEACESSO.CHAVE = CAST(pCHAVEACESSO AS VARCHAR(20));
 IF NOT FOUND THEN
    -- INEXISTENTE
    RETURN '0';
 ELSE
    -- EXISTE A CHAVE E PODE SER ALTERADA A LOCALIZAÇÃO NO APP.
    IF RCHAVEACESSO.ALTERARLOCALIZACAO = 1 THEN
       RETURN '1';
    END IF;

    -- EXISTE A CHAVE PORÉM NÃO PODE SER ALTERADA A LOCALIZAÇÃO NO APP
    IF RCHAVEACESSO.ALTERARLOCALIZACAO = 0 THEN
       RETURN '2';
    END IF;        
    
 END IF;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION getexistchaveacesso(text, text)
  OWNER TO postgres;
GRANT EXECUTE ON FUNCTION getexistchaveacesso(text, text) TO public;
GRANT EXECUTE ON FUNCTION getexistchaveacesso(text, text) TO postgres;
GRANT EXECUTE ON FUNCTION getexistchaveacesso(text, text) TO bal5nco;